name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [ test, test_with_split, test_without_split ]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install SQLite3 Libraries
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev
    - name: Install Gel
      run: |
        gem install gel
    - name: Install Gems
      run: |
        gel install
    - name: Run tests
      run: |
        gel exec rake ${{ matrix.task }}
